/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/

const fiboEvenSum = (n) => {

  let arr = [1, 2]

  // Insert the entire term in the Fibonacci sequence - until given number - into the array
  for (let i = arr[arr.length - 1] + arr[arr.length - 2]; i < n; i = i + arr[arr.length - 2]) {
    arr.push(i);
  };

  // Filtering a set of even numbers only, and connecting all numbers together
  return arr.filter(number =>  number % 2 === 0).reduce((sum, number) => sum + number);
}